[policy]
  # skip geo restriction; try to keep it worldwide for now
  # skip logging; too costly
  # skip WAF; too costly for now
  skip = [
    "AC_AWS_0486",
    "AC_AWS_0487",
    "AC_AWS_0493"
  ]