---
name: Super Linter on Entire Repo

on:
  workflow_dispatch:

jobs:
  super-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super Linter
        uses: docker://ghcr.io/github/super-linter:slim-latest
        with:
          entrypoint: /action/lib/linter.sh
        env:
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            LINTER_RULES_PATH: ./.github/linters
            TERRAFORM_TERRASCAN_CONFIG_FILE: .terrascan.toml
            YAML_LINTER_RULES_PATH: ./.github/linters/.yamllint.yaml
            VALIDATE_ALL_CODEBASE: true
            VALIDATE_TERRAFORM_TERRASCAN: true
            VALIDATE_JAVASCRIPT_ES: true
            VALIDATE_TYPESCRIPT_ES: true
            VALIDATE_JSX: true
            VALIDATE_YAML: true
            VALIDATE_JSON: true
            #VALIDATE_MARKDOWN: true
            VALIDATE_PYTHON_FLAKE8: true

